name: Build code

on: [push]
env:
    OPAMROOT: /home/user/.opam
    OPAMYES: true
    OPAMCONFIRMLEVEL: unsafe-yes
    latest: "./"
jobs:
    build:
        defaults:
            run:
                shell: bash
        runs-on: ubuntu-latest
        container:
            image: kakadu18/ocaml:fp2024
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}
            cancel-in-progress: true
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Installing dependencies for ${{ env.latest }}
              run: |
                  cd ${{ env.latest }} && opam install . --deps-only --yes
                  opam install ppx_deriving_qcheck --yes

            - if: false
              name: Checking ocamlformat
              run: |
                  cd ${{ env.latest }} && opam exec -- dune build @fmt --profile=release

            - name: Compiling ${{ env.latest }}...
              run: cd ${{ env.latest }} && opam exec -- dune build --profile=release

            - name: Running tests in ${{ env.latest }}...
              run: cd ${{ env.latest }} && opam exec -- dune runtest --profile=release
